# version: "3.8" # Docker ComposeAPI Version

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes: # 저장공간
      - ./app:/app
    command:
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000" # 장고를 실행하는 명령어
    # 0.0.0.0:8000 => 어떤 경로에서 접속을 해도 장고를 실행할 수 있음
    environment:
      - DB_HOST=db
      - DB_NAME=youtube
      - DB_USER=lolll
      - DB_PASS=pw123
    depends_on:
      - db # db 가 준비가 되면 컨테이너를 실행시켜

  db: # PostfreSQL Database
    image: postgres:16-alpine
    volumes: # 데이터를 어느 공간에 저장 해줄까
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=youtube
      - POSTGRES_USER=lolll
      - POSTGRES_PASSWORD=pw123